import { Injectable, Logger, type OnModuleInit } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import {
  Counter,
  Gauge,
  Histogram,
  Registry,
  collectDefaultMetrics,
} from 'prom-client';

/**
 * Prometheus metrics.
 *
 * A dedicated Registry rather than the library's global default: the global one
 * is process-wide shared state, and a second library that also uses prom-client
 * would silently register colliding metric names into it. An explicit registry
 * makes the collision an error at startup instead of a corrupted series.
 */
@Injectable()
export class MetricsService implements OnModuleInit {
  private readonly logger = new Logger(MetricsService.name);

  readonly registry = new Registry();

  /**
   * HTTP request duration.
   *
   * Buckets are chosen for this service's actual latency profile, not the
   * library defaults. The defaults top out at 10s, which puts every PDF export
   * and OCR request into `+Inf` — where they are invisible to a p95 query. The
   * long tail here is deliberate: those requests genuinely take tens of seconds
   * and the point of the histogram is to see when they get worse.
   */
  readonly httpDuration = new Histogram({
    name: 'http_request_duration_seconds',
    help: 'HTTP request duration in seconds',
    labelNames: ['method', 'route', 'status'] as const,
    buckets: [0.01, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 30, 60],
    registers: [this.registry],
  });

  readonly httpRequests = new Counter({
    name: 'http_requests_total',
    help: 'Total HTTP requests',
    labelNames: ['method', 'route', 'status'] as const,
    registers: [this.registry],
  });

  readonly httpInFlight = new Gauge({
    name: 'http_requests_in_flight',
    help: 'HTTP requests currently being served',
    registers: [this.registry],
  });

  /**
   * Readiness as a metric, not just a probe response.
   *
   * The probe tells Kubernetes; this tells the humans. Being able to graph how
   * many pods were unready during an incident is the difference between "the
   * database was slow" and "the database was slow and we lost four of six pods
   * for ninety seconds".
   */
  readonly ready = new Gauge({
    name: 'app_ready',
    help: '1 when the instance is ready to serve traffic, 0 while draining or unhealthy',
    registers: [this.registry],
  });

  readonly dependencyUp = new Gauge({
    name: 'app_dependency_up',
    help: '1 when a dependency check passed on the last readiness probe',
    labelNames: ['dependency'] as const,
    registers: [this.registry],
  });

  /** Business counters, exported so alerting can be written against them. */
  readonly notificationsSent = new Counter({
    name: 'notifications_sent_total',
    help: 'Notifications handed to a provider',
    labelNames: ['channel', 'outcome'] as const,
    registers: [this.registry],
  });

  readonly documentsGenerated = new Counter({
    name: 'documents_generated_total',
    help: 'Documents generated by the AI engine',
    labelNames: ['provider', 'outcome'] as const,
    registers: [this.registry],
  });

  readonly paymentsProcessed = new Counter({
    name: 'payments_processed_total',
    help: 'Payment gateway callbacks settled',
    labelNames: ['provider', 'outcome'] as const,
    registers: [this.registry],
  });

  private initialised = false;

  constructor(private readonly config: ConfigService) {}

  onModuleInit(): void {
    // Guarded because `collectDefaultMetrics` THROWS on a second call against
    // the same registry — prom-client refuses duplicate metric names. Nest calls
    // this once in production, but a test that also calls it explicitly, or a hot
    // reload, would otherwise take the whole application down at startup.
    if (this.initialised) return;
    this.initialised = true;

    // Heap, event-loop lag, GC pauses, open handles. Event-loop lag is the one
    // that matters most here: Tesseract's WASM recognition is synchronous and
    // will block the loop, and lag is how that shows up before it becomes
    // timeouts.
    collectDefaultMetrics({
      register: this.registry,
      prefix: 'legaltech_',
    });

    this.registry.setDefaultLabels({
      // Distinguishes pods once several replicas are scraped. Kubernetes sets
      // HOSTNAME to the pod name.
      instance: process.env.HOSTNAME ?? 'local',
      env: this.config.get<string>('NODE_ENV', 'development'),
    });

    this.ready.set(0);
    this.logger.log('Prometheus metrics registry initialised');
  }

  async scrape(): Promise<string> {
    return this.registry.metrics();
  }

  get contentType(): string {
    return this.registry.contentType;
  }
}

/**
 * Normalises a request path into a bounded label value.
 *
 * This is the single most important function in this file. Prometheus creates a
 * separate time series for every distinct label combination, so labelling with a
 * raw URL means `/documents/clx1.../export/pdf` becomes its own series — one per
 * document, forever. That is unbounded cardinality: it exhausts the scrape
 * target's memory first and then the Prometheus server's, and the usual way it
 * is discovered is an OOM in the monitoring stack during an incident.
 *
 * Nest exposes the matched route pattern on `req.route.path`, which is already
 * bounded. The fallback path below only runs when there is no matched route —
 * 404s, and anything handled before routing — and it collapses ids so a scan for
 * non-existent URLs cannot inflate the series count either.
 */
export function normalizeRoute(
  routePath: string | undefined,
  rawPath: string,
): string {
  if (routePath) return routePath;

  return (
    rawPath
      .split('?')[0]
      .split('/')
      .map((segment) => {
        if (!segment) return segment;
        // cuid / cuid2 — the id format this schema uses throughout.
        if (/^c[a-z0-9]{20,}$/i.test(segment)) return ':id';
        // uuid
        if (
          /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(
            segment,
          )
        ) {
          return ':id';
        }
        // Numeric ids, and anything long enough to be a token or a hash.
        if (/^\d+$/.test(segment)) return ':id';
        if (segment.length > 32) return ':id';
        return segment;
      })
      .join('/') || '/'
  );
}
